### PR TITLE
Add Vanguard 401(k) test file

### PR DESCRIPTION
**Pull request by m-d-brown**
Once this is in I plan to send some more PRs to improve 401(k) support.

### CODE REVIEW

**Comment by redstreet** [comment]
Excellent, thanks a ton. Tests with are sorely needed and most welcome. The pain of anonymizing keeps me from getting around to it.

**Comment by redstreet** [comment]
If you don't mind prefixing your commit message with `test: `, it makes releases easier. I try to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for messages.

**Comment by m-d-brown** [comment]
I've updated the commit message. I hadn't seen https://www.conventionalcommits.org/en/v1.0.0/ before -- makes sense!

I totally agree. Anonymizing is definitely a pain.

**Comment by redstreet** [comment]
Merged, thank you!

**Pull request merged**
