### PR TITLE
generate_transfer_entry: ensure other cash transfers point to cash_account

### PR DESCRIPTION
**Pull request by savingsandloan**
This PR clarifies `generate_transfer_entry` logic around how it facilitates:
- income/gain to cash transfers
- share to share transfers
- cash to cash transfers

Without this, there's an issue where transactions that could be either cash or share transfers (such as `dep`, which is outside of `['income', 'dividends', 'capgainsd_st', 'capgainsd_lt']`) end up pointing to towards the `main_account` rather than the `cash_account`.

I'm open to ideas in what to name the pairing end of `target_acct` - for the moment I called it `importer_acct` after realizing it can't be associated with source/destination.

### CODE REVIEW

**Comment by redstreet** [comment]
Hmm, cash or share transfers should involve `main_account` after my recent updates. `main_acct` would resolve to something like `Assets:Brokerage:AAPL` in the case of share transfers, and would  resolve to `Assets:Brokerage:USD` in the case of cash transfers.

It might help to include tests or examples to illustrate the examples you're pointing to.

I've updated the examples directory to show the config. See [my.import](https://github.com/redstreet/beancount_reds_importers/blob/main/beancount_reds_importers/example/my.import). Are you still seeing cases after using a config like this one? Thanks!

**Comment by savingsandloan** [comment]
Here's my example - The issue I was encountering was with this line of a deposit:

https://github.com/savingsandloan/beancount_reds_importers/blob/f9e2198ea4be195f417303f86a8792a9d9b4a675/beancount_reds_importers/fidelity_csv_hsa_test/History_for_Account_222222222.csv#L8

```
Run Date,Action,Symbol,Security Description,Security Type,Quantity,Price ($),Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
 12/01/2021, PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash), , No Description,Cash,,,,,,888,
```

Where there is both `cash_account` and `main_account` defined in the associated test configuration, similar to your my.import :  https://github.com/savingsandloan/beancount_reds_importers/blob/fidelity_csv_old/beancount_reds_importers/fidelity_csv_hsa_test/fidelity_csv_hsa_test.py  (Note: in this example I'm calling the cash_account `:Cash` instead of `:USD` as you have in my.import)

So, under the recent commit made ( https://github.com/redstreet/beancount_reds_importers/commit/7873656f90fc0cc6a7d8c0cad8a1ab0e95608fa1 ) in main, the test output observed is a reference to the `main_account` with no ticker appended for a cash deposit transfer:
```
2021-12-01 * "PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash)" "dep"
  __duplicate__: TRUE
  Assets:Fidelity:HSA              888 USD
  Assets:US:Fidelity:Checking          -888 USD
  Expenses:Investing:TradeCommissions
```

What one would expect is actually a reference to the `cash_account` for a cash deposit transfer:   
```
2021-12-01 * "PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash)" "dep"
  __duplicate__: TRUE
  Assets:Fidelity:HSA:Cash              888 USD
  Assets:US:Fidelity:Checking          -888 USD
  Expenses:Investing:TradeCommissions
```

The logic I'm proposing resolves this issue.

**Comment by redstreet** [comment]
Ah, got it. Here's a simpler fix: c010e009c107c69cb0d00d9197c50f8fd11c8fb3. Does that work, can you try it out? Am I missing anything?

**Comment by savingsandloan** [comment]
> Ah, got it, thanks! Here's a simpler fix: [c010e00](https://github.com/redstreet/beancount_reds_importers/commit/c010e009c107c69cb0d00d9197c50f8fd11c8fb3). Does that work, can you try it out? Am I missing anything?

ran my example test again, seems to work. Will close for now.

**Comment by savingsandloan** [comment]
NOTE: this logic in https://github.com/redstreet/beancount_reds_importers/commit/c010e009c107c69cb0d00d9197c50f8fd11c8fb3 is fine, but a note that if one is doing a cash-cash transfer and they are writing a custom `get_target_acct_custom` they will need to evaluate on `if(ticker is self.currency)` to direct towards the `cash_account` of the `target_acct` rather than the `main_account`

**Comment by redstreet** [comment]
Isn't it the "source" account that is the `cash_account`? Wouldn't the target account be the `transfer` account?

**Comment by savingsandloan** [comment]
> Isn't it the "source" account that is the `cash_account`? Wouldn't the target account be the `transfer` account?


> Wouldn't the target account be the `transfer` account?

Generally, yes, so you would just have a result of:

```
2021-12-01 * "PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash)" "dep"
  Assets:Fidelity:HSA:Cash              888 USD
  Assets:TransferTODO          -888 USD
  Expenses:Investing:TradeCommissions
```
if you have `transfer` setup to be `Assets:TransferTODO`

The comment was more in regard to a possibility of having additional support for detailed transfer accounts (configurable deduping rules, main/cash accounts, etc.) In such support you start to get concerned about whether you end up with the main account:

```
2021-12-01 * "PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash)" "dep"
  __duplicate__: TRUE
  Assets:Fidelity:HSA:Cash              888 USD
  Assets:US:Fidelity:Brokerage          -888 USD
  Expenses:Investing:TradeCommissions
```

...or the proper cash account: 

```
2021-12-01 * "PARTIC CONTR CURRENT VS X11-111111-1 CUR YR PARTICPNT CON (Cash)" "dep"
  __duplicate__: TRUE
  Assets:Fidelity:HSA:Cash              888 USD
  Assets:US:Fidelity:Brokerage:Cash          -888 USD
  Expenses:Investing:TradeCommissions
```

In case you're curious, this is how I was trying to play with such an idea in `fidelity_csv_old` :
 - Here's how a possible configuration around transfers would look: https://github.com/savingsandloan/beancount_reds_importers/blob/8e884084df35ceaa89f3c350eb454efeb37297b6/beancount_reds_importers/fidelity_csv_brokerage_test/fidelity_csv_brokerage_test.py#L23-L45
 
 - Here's how the `get_target_acct_custom` could look:
     https://github.com/savingsandloan/beancount_reds_importers/blob/8e884084df35ceaa89f3c350eb454efeb37297b6/beancount_reds_importers/fidelity_csv/__init__.py#L513

Again, that's for a different PR later on, but was just making a self-note around considerations

**Comment by redstreet** [comment]
Ah, got it. You're trying to handle both sides of the transfer in one single entry. I found that approach unworkable, as we've discussed before. Separating transfer-deduping from importing is key IMHO. Alternatives include:
- zerosum (which I use)
- Handling transfer-deduping at a layer that's separate from the importer. Eg: after you finish the imports, inferring transfer entries (from amounts, dates, and such), and merging them

Have you considered these by trying out a prototype? My guess is, it would simplify your transfer approach greatly. Anyway, that's my two cents, and I realize there are many ways to handle these :).

**Comment by redstreet** [comment]
One of beancount-reds-importers' principles is, the code *is* your importer config. From that perspective, your custom importer code is indeed a good place to put a couple of lines of code to handle your transfers if that's all is needed to handle your transfers. I don't see transfer deduping as within the scope of beancount-reds-importers, but there's no reason it won't work in your custom code.

**Comment by savingsandloan** [comment]
> Have you considered these by trying out a prototype?

> zerosum (which I use)

I'm aware of zerosum (and started playing with it for a certain usecase), leary of using it still for the original reasons mentioned on Red's Rants somewhere about seeking as few intermediary accounts as possible, fearing they could clutter other analytics/visualizations on a ledger.

> Handling transfer-deduping at a layer that's separate from the importer. Eg: after you finish the imports, inferring transfer entries (from amounts, dates, and such), and merging them. 

Understand the provocation around separation of concerns, I'll have to think about that a bit more. I see two things going on in my custom importer on this: 

- _Deduping feature_ - I can see how it's out of the scope of importers in general, and how there could be a separate 'deduping tool' , more on that in a sec.

- _More detailed naming of transfer accounts_ - whether it's a bank to bank transfer or something that might be more of a typical expense (i.e. `debit`), **do you feel that this is the responsibility of the importer?** I err a bit more towards yes on this so one can tell the importer about additional specific accounts when appropriate if it helps save a user time when reviewing. I know there's separate tools like `smart_importer` that, by configuration, 'hook' onto an importer to guess more detailed accounts, yet at the same time I find some of this to be more coupled to the specific importer - you may have a credit card that has special code categories to derive expense accounts, you may have a bank that has a certain way of sharing account info, etc.

Holding both deduping and detailed transfer accounts in mind, there's also questions that come up in terms of how information in a `.config` file gets organized as well to serve either the importer and/or a post-processing tool.

**Comment by redstreet** [comment]
> I'm aware of zerosum (and started playing with it for a certain usecase), leary of using it still for the original reasons mentioned on Red's Rants somewhere about seeking as few intermediary accounts as possible, fearing they could clutter other analytics/visualizations on a ledger.

I'd be curious to see if those concerns actually materalize. Just a thought.


>     * _More detailed naming of transfer accounts_ - whether it's a bank to bank transfer or something that might be more of a typical expense (i.e. `debit`), **do you feel that such a feature would be the responsibility of the importer?** I err a bit more towards yes on this so one can tell the importer about additional specific accounts when appropriate if it helps save a user time when reviewing. I know there's separate tools like `smart_importer` that, by configuration, 'hook' onto an importer to guess more detailed accounts, yet at the same time I find some of this to be more coupled to the specific importer - you may have a credit card that has special code categories to derive expense accounts, you may have a bank that has a certain way of sharing account info, etc.

Thanks, that's a good point to bring up. I view the importer as a foundation layer that decodes an institution provided file, makes straightforward decisions where it can, and calls hooks to outsource more complex or custom decisions.

This is why I exposed `get_target_acct_custom()`. It's essentially a hook, just like `smart_importer`, where you can write your own code, as simple or as complex as it may be, to make a decision about the target posting(s).

I make personal overrides like so:
```
from beancount_reds_importers import fidelity
def get_target_acct_custom(self, transaction, ticker=None):
   # make decisions here and return the target account based on transaction
fidelity.Importer.get_target_acct_custom = get_target_acct_custom
```

**Comment by savingsandloan** [comment]
> I view the importer as a foundation layer that decodes an institution provided file, makes straightforward decisions where it can, and calls hooks to outsource more complex or custom decisions. This is why I exposed get_target_acct_custom(). It's essentially a hook

Okay, between this and revisiting 'minimal, institution specific' in the readme, I'm starting to get the philosophy. It's trying to evolve past the older beancount sentiment around importers being private, yet have a structuring so an importer doesn't get too coupled to things.

> The cool thing about python is its friendliness to the "code-is-the-config" idea.

Yes, but I sense a 'science of tradeoffs' between code structure, the importer needing to parse out data to provide to "code-is-the-config" areas, conventions amongst importers, documentation, and where examples are shared (including "code-is-the-config" areas). 

For example, in fidelity_csv_old's importer approach, within `prepare_transactions_raw_columns` (called by `prepare_tables` which is called by csv_multitable.py's `read_file` ) it [parses out the 'transfer_account'](https://github.com/savingsandloan/beancount_reds_importers/blob/7ce5223681b2c539dc0b8418b81bd0fc33ce46cb/beancount_reds_importers/fidelity_csv/__init__.py#L776) into a separate column of information. This is then used by`[get_target_acct_custom](https://github.com/savingsandloan/beancount_reds_importers/blob/7ce5223681b2c539dc0b8418b81bd0fc33ce46cb/beancount_reds_importers/fidelity_csv/__init__.py#L519)` to find the detailed account name.

With that relationship in mind, the questions that come to mind in holding between 'importer' and 'configuration' are: 

- How should an institution-specific importer approach data that needs to be shared to any outside hooks? Should it have another hook within it's read/prepare function to call for a further 'custom' function? 

- If things like `get_target_acct_custom` or etc. are intended to be considered configuration (i.e. not in the importer), how does awareness of that get shared, especially if they carry components that might be useful to the next person trying to use such an importer? In the test file? In a separate repo sharing example configuration (if so, how does a user discover it)?  NOTE: assuming the author in such a scenario wants to share some contextual information to help save others time, and may already have knowledge from prior imports around some of the accounts & actions that may occur)

**Comment by redstreet** [comment]
> Okay, between this and revisiting 'minimal, institution specific' in the readme, I'm starting to get the philosophy. It's trying to evolve past the older beancount sentiment around importers being private, yet have a structuring so an importer doesn't get too coupled to things.

That's a good way to put it.

> The cool thing about python is its friendliness to the "code-is-the-config" idea.

> - **How should an institution-specific importer approach parsing data that needs to be shared to any outside hooks?** Should it have another hook within it's read/prepare function to call for a further 'custom' function?

With your example: the work in your transfer column is done individually for each row of input. Why not simply do that in `get_target_acct_custom()` instead?

For the generic case, simply override the method in question. Eg: `prepare_raw_columns`.

- **If things like `get_target_acct_custom` or etc. are intended to be considered configuration (i.e. not in the importer), how does awareness of that get shared**, especially if they carry components that might be useful to the next person trying to use such an importer? In the test file? In a separate repo sharing example configuration (if so, how does a user discover it)?  NOTE: assuming the author in such a scenario wants to share some contextual information to help save others time, and may already have knowledge from prior imports around some of the accounts & actions that may occur)

Great question. I agree with your intent completely in philosophy: importer architecture should allow the useful things about an importer to be shared easily. These remain open questions in my mind:
1. what are things worth sharing vs. not? Having an importer architecture that splits basic and extended functionality yields a lot of flexibility in answering this question. Bond related code, for example, becomes an optional  utility, meaning it can be shared without disrupting the basic importer
1. How to implement sharing?
  - An importer architecture that most folks can get behind would greatly allow the community to consolidate its efforts
  - A registry (like pypi) for importers and related utilities would allow one to do things like: search for Fidelity importers, understand the feature set of each, search for bond, transfer, and other utilities compatible with their fidelity importer, install all of them, and instantly have the whole thing working
  - Until the above happens, it's anyone's guess as to how to share them. I'm happy to add a contributions section and link to other repos or gists to help point people

**Comment by savingsandloan** [comment]
> With your example: the work in your transfer column is done individually for each row of input. Why not simply do that in get_target_acct_custom() instead?

`get_target_acct_custom(self, transaction, ticker=None)` assumes just the transaction and ticker are passed in. This isn't necessarily enough data unless one adds some columns to the transaction beforehand. which leads to your second phrase...

> For the generic case, simply override the method in question. Eg: prepare_raw_columns.

By saying override, are you suggesting that `prepare_raw_columns` would then also be parts of one's configuration instead as well?

> importer architecture should allow the useful things about an importer to be shared easily. These remain open questions in my mind:

I'll try to think about this more later, but yeah, the idea of how thing are shared (either by linking to other repos with custom), what helps one get towards a more 'batteries included' feeling, and the relationship between _beancount_reds_importers_ and the newer _beangulp_ effort.

**Comment by redstreet** [comment]
> > With your example: the work in your transfer column is done individually for each row of input. Why not simply do that in get_target_acct_custom() instead?
> 
> `get_target_acct_custom(self, transaction, ticker=None)` assumes just the transaction and ticker are passed in. This isn't necessarily enough data unless one adds some columns to the transaction beforehand. which leads to your second phrase...

`get_target_acct_custom()` is a method of the importer class :). It has full access to every `self` variable. For example, `transfer_account` is not needed as a column. Instead, simply use `self.__transfer_account_from_action(x["memo"])` inside `get_target_acct_custom` as needed.

**Pull request closed without merging**
