### PR TITLE
feat: Include unit price for investment transfers

### PR DESCRIPTION
**Pull request by m-d-brown**
This one is (hopefully!) much simpler to merge.

### CODE REVIEW

**Comment by redstreet** [comment]
Just to make sure I understand: aren't all three of the affected transactions in the test that are affected, `transfer`s? If so:
- shouldn't the other posting show up?
- to be consistent, shouldn't they have the lot specification in the `{XX USD}` notation?

**Comment by redstreet** [comment]
Hi @m-d-brown , just checking to see if you are still inclined to complete this PR and merge? Thanks!

**Comment by m-d-brown** [comment]
Apologies! I forgot about this and haven't since touched the associated logic in my personal use of Beancount. I'll close the PR and will send another when I think through the change more completely.

**Comment by redstreet** [comment]
No worries at all, and sounds good! 👍

**Pull request closed without merging**
