### PR TITLE
Enforce formatting

### PR DESCRIPTION
**Pull request by ranebrown**
Adds a job to check formatting and formats all existing files with ruff.

[Config options](https://docs.astral.sh/ruff/settings/#format) if you want anything changed from the defaults.

### CODE REVIEW

**Comment by redstreet** [comment]
Hello there, thanks for the PR! I think this is in general a good idea, and in particular helpful to keep contributions from multiple users consistent. However, it does seem to reduce readability in a few cases. I quickly highlighted a couple patterns, there are probably a few others. If you're familiar with ruff and its options, it'd be great if you could help figure out those cases at least, and I'd be happy to take it in. Thanks again!

**Comment by ranebrown** [comment]
I did a bit more digging and the option set is pretty limited. The ruff formatter pretty much matches [black](https://github.com/psf/black) which intentionally gives you very few options to change so all code formatted with it should look the same. For specific cases this can be done:

```python
# fmt: off
code_here()
...
#fmt: on
```

I would argue consistency across the board is better but let me know if you want formatting disabled on the sections you pointed out.

**Comment by redstreet** [comment]
Thanks for looking this up. You make a good point, and I agree overall. I still feel like `target_accounts_map` should be the one exception and remain unformatted, but I'm fine with leaving it to ruff on everything else for the sake of consistency. 

f you're okay making the change to exclude those blocks alone, I'd be happy to take it in. Thank you!

**Comment by ranebrown** [comment]
Made a few more changes:

1. Added exceptions for `transaction_type_map` and `header_map`.
2. Changed max line length to 88 which makes things more readable in most cases (easy to change back to 127 if you prefer).
3. Added [isort](https://pycqa.github.io/isort/) formatting
4. Moved ruff (and isort) config to a pyproject.toml file

**Comment by redstreet** [comment]
Looks great, I appreciate the PR and the changes! Merged. Thank you!

**Pull request merged**
