### PR TITLE
Add conftest.py for pytest --generate

### PR DESCRIPTION
**Pull request by savingsandloan**

### CODE REVIEW

**Review by redstreet — COMMENTED** [review]
This is something we need, so thanks!

Would you mind adding either an example or documentation on how to use it, so it doesn't feel like orphaned code that might end up being cleaned up later?

**Comment by savingsandloan** [comment]
Added documentation to README.md, won't have an example until I figure out the new fidelity_csv importer.

**Comment by redstreet** [comment]
@savingsandloan, I'm still not able to figure out how to use this from the README.md. Including one actual, real-world working test in this PR would help a lot.

**Comment by savingsandloan** [comment]
Got it, can see if I can make an example in a week or so that's based on existing importers (maybe schwab csv?) and which would help in having more instructions in the readme. 

In the meantime, if you're curious the [fidelity_csv_old](https://github.com/savingsandloan/beancount_reds_importers/commits/fidelity_csv_old) branch has demonstrations of the test directories and code structure - [fidelity csv brokerage test](https://github.com/savingsandloan/beancount_reds_importers/tree/fidelity_csv_old/beancount_reds_importers/fidelity_csv_brokerage_test) , [fidelity csv checking test](https://github.com/savingsandloan/beancount_reds_importers/tree/fidelity_csv_old/beancount_reds_importers/fidelity_csv_checking_test), [fidelisty csv hsa test](https://github.com/savingsandloan/beancount_reds_importers/tree/fidelity_csv_old/beancount_reds_importers/fidelity_csv_hsa_test) .

The test files all follow the basic structure of:

```

import unittest
import sys
from os import path

sys.path.insert(0, path.join(path.dirname(path.dirname(path.realpath(__file__)))))

from beancount.ingest import regression_pytest as regtest
import my_importer

[extra configuration lines to pass in]

IMPORTER = my_importer.Importer(
    {
        "currency": "USD",
        "account_number": "X99999999",
        "transfer": "Assets:TODOTransfer",
        [... other config values ...]
    }
)

@regtest.with_importer(IMPORTER)
@regtest.with_testdir(path.dirname(__file__))
class TestImporter(regtest.ImporterTestBase):
    pass

if __name__ == "__main__":
    unittest.main()
```

**Comment by redstreet** [comment]
@savingsandloan, closing this since it's been around for a while now, but feel free to reopen it any time you wish to resume. See my comment from April for what is pending.

**Comment by savingsandloan** [comment]
Got it, hope to eventually come back to this.

**Comment by redstreet** [comment]
Sure, any time!

**Pull request closed without merging**
